### PR TITLE
achilles6: Initial support for Lenovo M10 FHD Plus

### PR DESCRIPTION
**Pull request by UsrBinLuna**
title
yea its tested 🍡🍡🍡

### CODE REVIEW

**Comment by UsrBinLuna** [comment]
wait i forgot status.md :trhumbsup:

**Comment by halal-beef** [comment]
meh status is wip

also fix ur fb size

**Comment by halal-beef** [comment]
nvm its fixed, will merge when i fix mtk framebuffer format stuff

**Comment by halal-beef** [comment]
technically fixed so yeah

**Pull request merged**
